#### general settings
name: ir-sde
use_tb_logger: true
model: denoising
distortion: damaged_notes
gpu_ids: [0]

sde:
  max_sigma: 50
  T: 100
  schedule: cosine # linear, cosine
  eps: 0.005

degradation: # for some synthetic dataset that only have GTs
  # for denoising
  sigma: 50
  noise_type: G # Gaussian noise: G

  # for super-resolution
  scale: 1
  
#### datasets
datasets:
  train:
    name: Train_Dataset
    mode: ContextLQGT
    dataroot_GT: datasets/Example/LQ
    dataroot_LQ: datasets/Example/LQ
    dataroot_context: datasets/Example/Context

    use_shuffle: true
    n_workers: 1  # per GPU
    batch_size: 1
    GT_size: 100
    LR_size: 100
    use_flip: true
    use_rot: false
    color: RGB
  val:
    name: Val_Dataset
    mode: ContextLQGT
    dataroot_GT: datasets/Example/LQ
    dataroot_LQ: datasets/Example/LQ
    dataroot_context: datasets/Example/Context


#### network structures
network_G:
  which_model_G: ConditionalUNet
  setting:
    in_nc: 3
    out_nc: 3
    nf: 64
    depth: 4

#### path
path:
  pretrain_model_G: ~
  strict_load: true
  resume_state: ~

#### training settings: learning rate scheme, loss
train:
  optimizer: AdamW # Adam, AdamW, Lion
  lr_G: !!float 1e-4
  lr_scheme: TrueCosineAnnealingLR
  beta1: 0.9
  beta2: 0.99
  niter: 200000
  warmup_iter: -1  # no warm up
  lr_steps: [60000, 120000, 180000]
  lr_gamma: 0.5
  eta_min: !!float 1e-7

  # criterion
  is_weighted: False
  loss_type: l1
  weight: 1.0

  manual_seed: 0
  val_freq: !!float 25e2

#### logger
logger:
  print_freq: 50
  save_checkpoint_freq: !!float 1e4
